### ISSUE TITLE
Complection doesn't display.

### ISSUE THREAD

**Issue by WALL-EEEEEEE** [Quramy/vison#4]
I have tried this awesome plugin for a while but got nothing. Frankly, then ,I followed operations as the tutorial README.I opened a package.json file for a tthen,  call :Vison  to active.All of above work fine, but when I enter the content in the file, nothing get responded, not as the screenshot showed.I don't know why.That should be mentioned I used <Tab> mapping to <C-x><C-o>.I don't know if it affected.

**Comment by with0out** [comment]
Me too can't seem to get it to work.
"set omnifunc" returns

```
omnifunc=vison#complete
```

But <kbd>C-x</kbd> <kbd>C-o</kbd> gives nothing.
Can someone point me at the right direction please?
